[book]
authors = ["Nnamllit11"]
language = "en"
src = "src"
title = "nrbbr3d Engine Wiki"
description = "The official wiki for the nrbbr3d Engine"

[output.html]
git-repository-url = "https://github.com/Nnamllit1/nrbbr3d-Engine-V2-Wiki"
edit-url-template = "https://github.com/Nnamllit1/nrbbr3d-Engine-V2-Wiki/edit/main/{path}"
